services:
  - type: web
    name: loan-default-system
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --threads 2 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MONGODB_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.0
